apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-ucxsm2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ucxsm2
  namespace: my-nginx-ucxsm2
  labels:
    name: nginx-ucxsm2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ucxsm2
  template:
    metadata:
      namespace: my-nginx-ucxsm2
      labels:
        name: nginx-ucxsm2
    spec:
      containers:
      - name: nginx-ucxsm2
        image: nginx
        ports:
        - containerPort: 80

